name: CMake CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run-cmake
      uses: lukka/run-cmake@v0.5
      with:
        # Select the build configuration, typically Debug or Release.
        cmakeBuildType: Debug # optional, default is Debug
