name: Build HercControl

on: [push]

jobs:
  job:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
    steps:
    - name: Checkout HercControl
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Run CMAKE
      uses: lukka/run-cmake@v0.5
      with:
        # Select the build configuration, typically Debug or Release.
        cmakeBuildType: Release # optional, default is Debug
        buildDirectory: "${{ runner.temp }}/build"
    - name: Get Executable
      run: |
        mkdir -p "${{ runner.temp }}/exe"
        cp "${{ runner.temp }}/build/HercControl" "${{ runner.temp }}/exe" || true
        cp "${{ runner.temp }}/build/HercControl.exe" "${{ runner.temp }}/exe" || true
        ls "${{ runner.temp }}/exe"
      shell: bash

    - name: Make Sanity Check
      # Makes a invalid call (no args) and expects RC=2
      working-directory: ${{ runner.temp }}/exe
      run: | 
        echo '#!/bin/bash'                    >  sanity.sh
        echo './HercControl'                  >> sanity.sh
        echo 'if [ $? -eq 2 ]'                >> sanity.sh
        echo 'then'                           >> sanity.sh
        echo '  echo "Sanity Check OK"'       >> sanity.sh
        echo '  exit 0'                       >> sanity.sh
        echo 'else'                           >> sanity.sh
        echo '  echo "Sanity Check Failed"'   >> sanity.sh
        echo '  exit 1'                       >> sanity.sh
        echo 'fi'                             >> sanity.sh
        chmod +x sanity.sh
      shell: bash

    - name: Upload Executable
      uses: actions/upload-artifact@v1
      with:
        name: HercControl-for-${{ matrix.os }}
        path: "${{ runner.temp }}/exe"

    - name: Sanity Check
      working-directory: ${{ runner.temp }}/exe
      run: | 
        bash sanity.sh
      shell: bash
