name: Build HercControl

on: [push]

jobs:
  job:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
    steps:
    - name: Checkout HercControl
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Run CMAKE
      uses: lukka/run-cmake@v0.5
      with:
        # Select the build configuration, typically Debug or Release.
        cmakeBuildType: Release # optional, default is Debug
        buildDirectory: "${{ runner.temp }}/build"
    - name: Get Executable
      run: |
        mkdir -p "${{ runner.temp }}/exe"
        cp "${{ runner.temp }}/build/HercControl" "${{ runner.temp }}/exe" || true
        cp "${{ runner.temp }}/build/HercControl.exe" "${{ runner.temp }}/exe" || true
        ls "${{ runner.temp }}/exe"
      shell: bash
    - name: Upload Executable
      uses: actions/upload-artifact@v1
      with:
        name: HercControl-for-${{ matrix.os }}
        path: "${{ runner.temp }}/exe"
